### ISSUE TITLE
To do list - milestone 3 (hopefully)

### ISSUE THREAD

**Issue by mkeyim** [UBC-MDS/wine_viz_mkpv#19]
- [x] Improve repo  README
- [x] Add in "Price Category" column to filter instead of having slider
- [x] Add in an explanatory viz sentence (i.e. "This is an exploratory wine application..")
- [x] Change "width" of filter bar
- [x] Conditional filters, fix the filters 
- [x] Add in colour bar for map
- [x] Make vintage filter functional 
- [x] Make region filter functional
- [x] Price range should be labeled (USD$)
- [x] Error message, try to do something with the exception handling - explain the error
- [ ] Try to make map interactive 
- [x] Try to give user instructions
- [ ] Make variety plot filterable by selecting variety
- [x] Review coding practices with TA - Paul to update

**Comment by mkeyim** [comment]
finished all that we could do within time frame
