### ISSUE TITLE
Feedback milestone 2

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/wine_viz_mkpv#22]
Great!

- Visually appealing color scheme.
- Can you remove the first number in the tooltip? It seems redundant. Consider removing the tooltip altogether for countries without data.
- When you deselect all countries you get an error. Print a more useful help message instead or show empty plots.
- Nice with the option to select and deselect all entries.
- The price range filter goes to 10,000, but the scatter plot shows that the most expensive wine is 800USD, why is this? 
- When I select regions and vintage years, nothing updates in the plots. Are these not implemented yet?
- Nice touch coloring the bars according to value. Maybe make the faintest bars a bit more visible (could especially be a problem for visually impaired people). Don't worry about them being compacted along the y-axisdue to some very high vaues, since it is possible to zoom in this is sue is largely alleviated (you could also have a toggling for including/excluding extreme values). 
- You have an issue with saturation for the categorical scatter plot. Consider using swarm/hive plots and smaller markers rather than transparency to better show the distribution of each rating.
- There is no need for the y-label "variety" in the bar plot. I would also rotate the y-ticklabels to be horizontal rather than diagonal. If you have long names, consider an abbreviation.
- This sentence is a bit vague: "The original goal of our application was to make an exploratory wine application, **and I believe that is still our goal**" (em added).

**Comment by mkeyim** [comment]
- [x] Can you remove the first number in the tooltip? It seems redundant. 
- [x] Consider removing the tooltip altogether for countries without data.
- [x] When you deselect all countries you get an error. Print a more useful help message instead or show empty plots.
- [x] The price range filter goes to 10,000, but the scatter plot shows that the most expensive wine is 800USD, why is this? *This has been fixed, the most expensive wine was getting automatically filtered by plotly*
- [x] When I select regions and vintage years, nothing updates in the plots. Are these not implemented yet? *These have been implemented*
- [x] Nice touch coloring the bars according to value. Maybe make the faintest bars a bit more visible (could especially be a problem for visually impaired people). Don't worry about them being compacted along the y-axisdue to some very high vaues, since it is possible to zoom in this is sue is largely alleviated (you could also have a toggling for including/excluding extreme values).
- [x] You have an issue with saturation for the categorical scatter plot. Consider using swarm/hive plots and smaller markers rather than transparency to better show the distribution of each rating.
- [x] There is no need for the y-label "variety" in the bar plot. I would also rotate the y-ticklabels to be horizontal rather than diagonal. If you have long names, consider an abbreviation.

@Pall-v
